apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gzzh7llzu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gzzh7llzu-go 
  name: gzzh7llzu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gzzh7llzu-go 
